- name: Reinstall REST Proxy
  hosts: kafka_rest
  vars_prompt:
    - name: reinstall_rest
      prompt: "Reinstall REST Proxy? [yes(default)/no]"
      private: no
      default: true
  tasks:
    - block:
        - import_role:
            name: confluent.variables_handlers
        - import_role:
            name: confluent.common
        - name: Reinstall REST Proxy
          include_tasks: tasks/reinstall_and_restart_components.yml
          vars:
            tmp_name: "rest"
            services:
              - "{{ kafka_rest_service_name }}"
            # schema registry packages might be needed by rest proxy for AVRO stuff. Not sure about control center, might also need it.
            packages: "{{ (kafka_rest_packages + control_center_packages + schema_registry_packages) | unique}}"
            backup_files:
              - "{{ kafka_rest.config_file }}"
              - "{{ kafka_rest.systemd_override }}"
            restore_files:
              - "{{ kafka_rest.config_file }}"
      when: reinstall_rest|bool
    - debug:
        msg: "Skip reinstalling REST Proxy"
      when: not reinstall_rest|bool