- name: Reinstall ZK and Kafka
  hosts: zookeeper:kafka_broker
  vars_prompt:
    - name: reinstall_zk_kafka
      prompt: "Reinstall ZK and Kafka? [yes(default)/no]"
      private: no
      default: true
  tasks:
    - block:
        - import_role:
            name: confluent.variables_handlers
        - import_role:
            name: confluent.common
        - name: Stop Kafka
          systemd:
            name: "{{ kafka_broker_service_name }}"
            state: stopped
        - name: Stop ZK
          systemd:
            name: "{{ zookeeper_service_name }}"
            state: stopped
        - name: Reinstall ZK and Kafka
          include_tasks: tasks/reinstall_components.yml
          vars:
            tmp_name: "zk_and_kafka"
            packages: "{{ (zookeeper_packages + kafka_broker_packages) | unique}}"
            backup_files:
              - "{{ kafka_broker.config_file }}"
              - "{{ kafka_broker.systemd_override }}"
              - "{{ zookeeper.config_file }}"
              - "{{ zookeeper.systemd_override }}"
            restore_files:
              - "{{ kafka_broker.config_file }}"
              - "{{ zookeeper.config_file }}"
        - name: Restart Zookeeper
          import_tasks: tasks/restart_zookeeper.yml
        - name: Restart Kafka Brokers
          import_tasks: tasks/restart_kafka.yml
      when: reinstall_zk_kafka|bool
    - debug:
        msg: "Skip reinstalling Zookeeper and Kafka"
      when: not reinstall_zk_kafka|bool