- name: Start Kafka
  systemd:
    name: "{{ kafka_broker_service_name }}"
    state: restarted
    daemon_reload: yes

- name: Wait for Under Replicated Partitions on Broker
  import_tasks: tasks/wait_for_urp.yml