- name: Start ZK
  systemd:
    name: "{{ zookeeper_service_name }}"
    state: restarted
    daemon_reload: yes

- name: Wait for Zookeeper Status
  shell: echo srvr | nc localhost 2181
  register: srvr
  until: srvr.rc == 0
  retries: 30
  delay: 5

- name: Wait for Zookeeper Quorum
  shell: echo srvr | nc localhost 2181
  register: srvr
  until: '"Latency min/avg/max:" in srvr.stdout'
  retries: 30
  delay: 5